# 文本分类实例

## Step1 导入相关包

In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

## Step2 加载数据

In [2]:
import pandas as pd

# 数据集是 https://github.com/SophonPlus/ChineseNlpCorpus
data = pd.read_csv("./ChnSentiCorp_htl_all.csv")
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7766 rows x 2 columns]

In [3]:
# 去掉空行
data = data.dropna()
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7765 rows x 2 columns]

In [4]:
data.iloc[0]

label                                                     1
review    距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
Name: 0, dtype: object

In [5]:
data.iloc[0]["review"]

'距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较为简单.'

In [6]:
data.iloc[0]["label"]

np.int64(1)

## Step3 创建 Dataset

In [7]:
from torch.utils.data import Dataset


class MyDataset(Dataset):

    def __init__(self) -> None:
        super().__init__()
        self.data = pd.read_csv("./ChnSentiCorp_htl_all.csv")
        self.data = self.data.dropna()

    def __getitem__(self, index):
        return self.data.iloc[index]["review"], self.data.iloc[index]["label"]

    def __len__(self):
        return len(self.data)

In [8]:
dataset = MyDataset()
for i in range(5):
    print(dataset[i])

('距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较为简单.', np.int64(1))
('商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!', np.int64(1))
('早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。', np.int64(1))
('宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小，但加上低价位因素，还是无超所值的；环境不错，就在小胡同内，安静整洁，暖气好足-_-||。。。呵还有一大优势就是从宾馆出发，步行不到十分钟就可以到梅兰芳故居等等，京味小胡同，北海距离好近呢。总之，不错。推荐给节约消费的自助游朋友~比较划算，附近特色小吃很多~', np.int64(1))
('CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风', np.int64(1))

## Step4 划分数据集

In [9]:
from torch.utils.data import random_split


trainset, validset = random_split(dataset, lengths=[0.9, 0.1])
len(trainset), len(validset)

(6989, 776)

In [10]:
for i in range(10):
    print(trainset[i])
    print(trainset[i][0])
    print(trainset[i][1])
    print()

('不知道什么原因，这个酒店目前的价格做了下调，而且周末居然有促销价。不错！这次入住的是大床房，依旧是紧促的布局，舒服的床，总体来说，还是很不错的！', np.int64(1))
不知道什么原因，这个酒店目前的价格做了下调，而且周末居然有促销价。不错！这次入住的是大床房，依旧是紧促的布局，舒服的床，总体来说，还是很不错的！
1

('首先酒店所在位置很隐蔽，看样子是网上订单的客人比较多，价格便宜，相对的房间硬件设施和服务就差些。我房子的空调竟然是个二手的。上面还贴着大头照。前台对你也爱理不理的。如果囊中羞涩可以考虑该酒店，否则还是去别处吧。第二天换的那个不远的天财酒店还不错。价格也合理328元', np.int64(0))
首先酒店所在位置很隐蔽，看样子是网上订单的客人比较多，价格便宜，相对的房间硬件设施和服务就差些。我房子的空调竟然是个二手的。上面还贴着大头照。前台对你也爱理不理的。如果囊中羞涩可以考虑该酒店，否则还是去别处吧。第二天换的那个不远的天财酒店还不错。价格也合理328元
0

('房间有法式风格，尤其浴室和化妆间的布置。不过淋浴房的防水做的不好，洗完澡浴室地面全是水，差点摔跤。宾馆反馈2008年4月11日：非常感谢您的光临和对我们饭店的关注和肯定。对于您提出的不足我们将努力改进，力求把工作做得更好，给宾客提供更优质、更舒适的硬件设施和软件服务。', np.int64(1))
房间有法式风格，尤其浴室和化妆间的布置。不过淋浴房的防水做的不好，洗完澡浴室地面全是水，差点摔跤。宾馆反馈2008年4月11日：非常感谢您的光临和对我们饭店的关注和肯定。对于您提出的不足我们将努力改进，力求把工作做得更好，给宾客提供更优质、更舒适的硬件设施和软件服务。
1

('位置还行,而且旁边就有个1+1超市.唯一让我不爽的是,入住后不到一小时,因行程有变,要退房,竟然称收半天房租!!!而我入住后就去吃饭,怎么样都不肯让步,真郁闷!!!看来还是住石歧好了.', np.int64(0))
位置还行,而且旁边就有个1+1超市.唯一让我不爽的是,入住后不到一小时,因行程有变,要退房,竟然称收半天房租!!!而我入住后就去吃饭,怎么样都不肯让步,真郁闷!!!看来还是住石歧好了.
0

('之前就听说苏州万丽是苏州生意最好，房价最高，也是业内人士最推崇的酒店，远胜于喜来登，香格里拉，索菲特，在苏州属于一枝独秀型的，平时房间非常的难定，几乎天天满房，这次好不容易定了个行政套，本打算住一天，后又延了一天，简单来说吧，房间不大但很温馨，酒店工作人员不多但都非常专业，亲切，严格意义上来说该酒店硬件并不突出，没有游泳池，没有特色餐厅，建筑也没有什么特色，处处透露着简单，适用，大气，但是只有你住了以后才会觉得，值！。。。。。。。还记得苏州迷宫喜来登的恐怖经历，差点把我绕死。。。。。。。。。。。。。下次只要有房间，肯定住他。', np.int64(1))
之前就听说苏州万丽是苏州生意最好，房价最高，也是业内人士最推崇的酒店，远胜于喜来登，香格里拉，索菲特，在苏州属于一枝独秀型的，平时房间非常的难定，几乎天天满房，这次好不容易定了个行政套，本打算住一天，后又延了一天，简单来说吧，房间不大但很温馨，酒店工作人员不多但都非常专业，亲切，严格意义上来说该酒店硬件并不突出，没有游泳池，没有特色餐厅，建筑也没有什么特色，处处透露着简单，适用，大气，但是只有你住了以后才会觉得，值！。。。。。。。还记得苏州迷宫喜来登的恐怖经历，差点把我绕死。。。。。。。。。。。。。下次只要有房间，肯定住他。
1

('我于4月底入住该酒店，整体来说该酒店超出我的预期。酒店门口有公交车站，多路公交车经过；还有出租车在门口，打车也很方便。酒店客房层设有中庭，宽敞明亮，让人感觉眼前一亮。标房面积很大，还配有电脑提供免费上网。服务员非常热情，能主动问候并提供建议。某种程度上感觉是五星级酒店，下次还会来。', np.int64(1))
我于4月底入住该酒店，整体来说该酒店超出我的预期。酒店门口有公交车站，多路公交车经过；还有出租车在门口，打车也很方便。酒店客房层设有中庭，宽敞明亮，让人感觉眼前一亮。标房面积很大，还配有电脑提供免费上网。服务员非常热情，能主动问候并提供建议。某种程度上感觉是五星级酒店，下次还会来。
1

('酒店环境还不错，只是床真的是太软了，不习惯。早餐过于简单，且每天早上都一样。宾馆反馈2008年6月13日：首先感谢您入住我们酒店，客栈的床是惰性海绵，有舒缓解压，特别是对脊椎有良好的治疗作用。如果感觉太软，有硬席可加，这样就跟普通的床一样了。早餐我们是分A套和B套任选一种的方式，对续住的客人而言，可以两种都品尝。如果有机会，真诚的希望您能再次光临我们酒店！', np.int64(1))
酒店环境还不错，只是床真的是太软了，不习惯。早餐过于简单，且每天早上都一样。宾馆反馈2008年6月13日：首先感谢您入住我们酒店，客栈的床是惰性海绵，有舒缓解压，特别是对脊椎有良好的治疗作用。如果感觉太软，有硬席可加，这样就跟普通的床一样了。早餐我们是分A套和B套任选一种的方式，对续住的客人而言，可以两种都品尝。如果有机会，真诚的希望您能再次光临我们酒店！
1

('我订的是祥和楼,房间和设施都很陈旧,看了房之后给携程打电话换成了泰和楼.房间还不错,是新装修的.美中不足是早餐时间太早,9点多就没了,没吃到.值得一提的是该酒店不时会有一些促销活动,比如我们当时订的是三间房,而酒店当时买三送一,也就是说订三间免费送一间,人多的话挺合适的,订房时问一问前台（订房时携程没说）,可以同时享受携程价格的．', np.int64(1))
我订的是祥和楼,房间和设施都很陈旧,看了房之后给携程打电话换成了泰和楼.房间还不错,是新装修的.美中不足是早餐时间太早,9点多就没了,没吃到.值得一提的是该酒店不时会有一些促销活动,比如我们当时订的是三间房,而酒店当时买三送一,也就是说订三间免费送一间,人多的话挺合适的,订房时问一问前台（订房时携程没说）,可以同时享受携程价格的．
1

('强烈不推荐本酒店。通过携程预定了一间大床房，房价580元，单早，增加一份早餐68元，当时我们以为五星标准。晚上飞机误点，到达酒店已经11点多了，以为在郊县，外面看酒店灯光昏暗，真没看出五星标准，相比上海的一些三星还不如。壮着胆子进了酒店，只有一位女服务生在前台。然后在只有我们两个人的情况下，花十几分钟给我们办好了入住手续。我们因为没吃晚饭，打算去市区吃宵夜。居然--酒店外面没有出租车了。当时晚上十二点左右。而且马路上没人没车。（烟台机场到酒店的时候，叫的出租车的驾驶员说华美达酒店到市区车程大约三十分钟，我们从机场到酒店花了二十分钟。）只好先进房间叫餐，幸亏还有叫餐服务。进了房间，真的吓一跳，装修还不错，可是面积奇小，一张普通大床加床头柜居然占据了房间一半的面积。打开窗户，看到的是酒店内部中庭。叫餐也是单子上的几乎没有，只有几种炒饭和面。我们恍惚不是身处城市。但是这可是我出发前认真选择的，大家好评如潮的酒店呀。吃饭的时候我找到了原因：写字台上有一张广告，上面内容是购买我们入住的酒店，可以代为管理营业，又可以每年用于自住N天，是一种理想的投资方式。原来这个酒店是由很多个人购买的，由酒店集中管理经营的，收益是回报那些购买者的。这大概就是好评如潮的原因了：谁不想自己的投资有个好回报啊。至于次日68元一份的早餐，五星收费，三星标准。我们第三天在威海的四星酒店早餐，比这里好些，收28元每位。概况地说：酒店交通不便，服务一般，装修较新较时尚，如果房价在三百以下，客人又不需要去市区的，还是可以入住的。宾馆反馈2008年8月7日：23点以后，酒店外的灯只保留照明路灯；夜间总台有两名员工当班，出现1名员工服务，是因为另一名员工暂时有事离岗；希望客人谅解！酒店的西餐厅提供送餐服务，西餐品种较多，酒店会考虑适时增加部分中餐品种。', np.int64(0))
强烈不推荐本酒店。通过携程预定了一间大床房，房价580元，单早，增加一份早餐68元，当时我们以为五星标准。晚上飞机误点，到达酒店已经11点多了，以为在郊县，外面看酒店灯光昏暗，真没看出五星标准，相比上海的一些三星还不如。壮着胆子进了酒店，只有一位女服务生在前台。然后在只有我们两个人的情况下，花十几分钟给我们办好了入住手续。我们因为没吃晚饭，打算去市区吃宵夜。居然--酒店外面没有出租车了。当时晚上十二点左右。而且马路上没人没车。（烟台机场到酒店的时候，叫的出租车的驾驶员说华美达酒店到市区车程大约三十分钟，我们从机场到酒店花了二十分钟。）只好先进房间叫餐，幸亏还有叫餐服务。进了房间，真的吓一跳，装修还不错，可是面积奇小，一张普通大床加床头柜居然占据了房间一半的面积。打开窗户，看到的是酒店内部中庭。叫餐也是单子上的几乎没有，只有几种炒饭和面。我们恍惚不是身处城市。但是这可是我出发前认真选择的，大家好评如潮的酒店呀。吃饭的时候我找到了原因：写字台上有一张广告，上面内容是购买我们入住的酒店，可以代为管理营业，又可以每年用于自住N天，是一种理想的投资方式。原来这个酒店是由很多个人购买的，由酒店集中管理经营的，收益是回报那些购买者的。这大概就是好评如潮的原因了：谁不想自己的投资有个好回报啊。至于次日68元一份的早餐，五星收费，三星标准。我们第三天在威海的四星酒店早餐，比这里好些，收28元每位。概况地说：酒店交通不便，服务一般，装修较新较时尚，如果房价在三百以下，客人又不需要去市区的，还是可以入住的。宾馆反馈2008年8月7日：23点以后，酒店外的灯只保留照明路灯；夜间总台有两名员工当班，出现1名员工服务，是因为另一名员工暂时有事离岗；希望客人谅解！酒店的西餐厅提供送餐服务，西餐品种较多，酒店会考虑适时增加部分中餐品种。
0

('说真的房间的设施和质量只当内地的3星水平不到不过还是很清静早餐是免费的靠近金沙要走7-8分钟到新葡京要走20分钟总体来说还算OK我想这大概就是澳门比较老的酒店了比起其他大的酒店价格上还是有竞争力的', np.int64(1))
说真的房间的设施和质量只当内地的3星水平不到不过还是很清静早餐是免费的靠近金沙要走7-8分钟到新葡京要走20分钟总体来说还算OK我想这大概就是澳门比较老的酒店了比起其他大的酒店价格上还是有竞争力的
1

In [11]:
for i in range(10):
    print(validset[i])
    print(validset[i][0])
    print(validset[i][1])
    print()

('周边环境不太好，比较乱。房间设施简陋，收费偏贵。服务不太到位，中午1点你正在休息时，服务员来打扰要清理房间,真是令人烦恼。结果让他们下午晚些来，结果这一天房间也没打扫。这样的服务在别处是不可能遇到的。', np.int64(0))
周边环境不太好，比较乱。房间设施简陋，收费偏贵。服务不太到位，中午1点你正在休息时，服务员来打扰要清理房间,真是令人烦恼。结果让他们下午晚些来，结果这一天房间也没打扫。这样的服务在别处是不可能遇到的。
0

('很破的宾馆，号称四星不过实际的情况比好一点的2星都差，早饭也是惨不忍睹。', np.int64(0))
很破的宾馆，号称四星不过实际的情况比好一点的2星都差，早饭也是惨不忍睹。
0

('不错的酒店。就是早餐水果太单调。宽带直接连电信网的，速度很快。', np.int64(1))
不错的酒店。就是早餐水果太单调。宽带直接连电信网的，速度很快。
1

('酒店介绍和实际不符，达不到3星级标准，房间不紧张，还要求信用卡担保。到达现场后，客人不满意，最后选择宁可酒店扣除了房费，也选择了喀什的其他的酒店，那就是携程也未推荐的中西亚国际大酒店，价格和其相仿，但是其为四星标准。而且，携程与酒店的沟通做得不好，明明是酒店的介绍与实际有较大的偏差，而且价格比起当地旅行社的价格要高出30%，可是酒店方面还是扣除了我们订房的全部房费，我同样要考虑是否还继续使用携程作为我的选择。', np.int64(0))
酒店介绍和实际不符，达不到3星级标准，房间不紧张，还要求信用卡担保。到达现场后，客人不满意，最后选择宁可酒店扣除了房费，也选择了喀什的其他的酒店，那就是携程也未推荐的中西亚国际大酒店，价格和其相仿，但是其为四星标准。而且，携程与酒店的沟通做得不好，明明是酒店的介绍与实际有较大的偏差，而且价格比起当地旅行社的价格要高出30%，可是酒店方面还是扣除了我们订房的全部房费，我同样要考虑是否还继续使用携程作为我的选择。
0

('本次的预定是帮我同事的,据他们在酒店的感受.....总的来说很不满意!第一,该酒店说是2006年开业,实际上是2006年从别人手中接转过来的,不知道具体是哪一年的酒店,酒店设施很旧;第二,入住的当天,因预定同前台没有沟通,差点导致客人没有房间(结果通过携程的协助才得到解决:通过携程预定成功,但酒店没有留房),后来好象是抽调出的两个房间;第三,入住酒店1015房间情况:流出的水比较脏,风筒也是坏的,报修了很久都没有结果,最后还是通过携程协助才搞定那个风筒;第四,酒店服务员对客人的态度比较不好,1015房洗手间内没有浴缸,客人问是否带浴缸的房间,服务人员说没有,结果客人第二天早上路过1011房间时,通过开着的门看到该房间恰有浴缸,不明白服务员为什么要欺骗客人;第五,早餐时,餐厅服务人员竟然替客人签早餐账单(据后来通过携程调查后,由该酒店前台服务人员电话说是这样的,因当时怀疑属前台设置了相同房间的两张房卡,但其销售部经理说不可能会发生这样的事---感受非常不安全),虽说只有30元钱,但对待客人的态度恶劣---不相信客人有支付能力,怕客人逃单;员工培训不到位,不知道如何服务;最后,我们以后去北京一定不会再去住这家酒店了,也不会再推荐朋友或是同事入住这家酒店的.补充点评2007年10月23日：入住及退房都因为上述情况而耽误了很多的时间!不会考虑帮客人节约时间!', np.int64(0))
本次的预定是帮我同事的,据他们在酒店的感受.....总的来说很不满意!第一,该酒店说是2006年开业,实际上是2006年从别人手中接转过来的,不知道具体是哪一年的酒店,酒店设施很旧;第二,入住的当天,因预定同前台没有沟通,差点导致客人没有房间(结果通过携程的协助才得到解决:通过携程预定成功,但酒店没有留房),后来好象是抽调出的两个房间;第三,入住酒店1015房间情况:流出的水比较脏,风筒也是坏的,报修了很久都没有结果,最后还是通过携程协助才搞定那个风筒;第四,酒店服务员对客人的态度比较不好,1015房洗手间内没有浴缸,客人问是否带浴缸的房间,服务人员说没有,结果客人第二天早上路过1011房间时,通过开着的门看到该房间恰有浴缸,不明白服务员为什么要欺骗客人;第五,早餐时,餐厅服务人员竟然替客人签早餐账单(据后来通过携程调查后,由该酒店前台服务人员电话说是这样的,因当时怀疑属前台设置了相同房间的两张房卡,但其销售部经理说不可能会发生这样的事---感受非常不安全),虽说只有30元钱,但对待客人的态度恶劣---不相信客人有支付能力,怕客人逃单;员工培训不到位,不知道如何服务;最后,我们以后去北京一定不会再去住这家酒店了,也不会再推荐朋友或是同事入住这家酒店的.补充点评2007年10月23日：入住及退房都因为上述情况而耽误了很多的时间!不会考虑帮客人节约时间!
0

('这酒店真的不咋样，一进房间，就闻到一股地毯发出的异味，晚上睡觉时，房间弥漫着一股厕所的异味（估计是中央空调的送风口送出来的），很是难受，我住了两天只好仓惶而逃。而且通过携程预定明明可以免费升级至豪华间，但酒店只是升至商务间，和酒店交涉，酒店前台人员居然说豪华间还不如商务间（豪华间518，商务间才458），那岂不是自打嘴巴，订豪华间的客人岂不都是傻子？总之，郁闷！', np.int64(0))
这酒店真的不咋样，一进房间，就闻到一股地毯发出的异味，晚上睡觉时，房间弥漫着一股厕所的异味（估计是中央空调的送风口送出来的），很是难受，我住了两天只好仓惶而逃。而且通过携程预定明明可以免费升级至豪华间，但酒店只是升至商务间，和酒店交涉，酒店前台人员居然说豪华间还不如商务间（豪华间518，商务间才458），那岂不是自打嘴巴，订豪华间的客人岂不都是傻子？总之，郁闷！
0

('4月份回青岛顺便带朋友去玩的，为他们选择的就是该酒店，房间干净整洁，但是卫生间的设施太简陋，房间内有小冰箱，考虑的比较周到，如果卫生间设备好一点就更好了！服务人员的态度非常好，没有给我们青岛人丢脸，电话随叫随到。', np.int64(1))
4月份回青岛顺便带朋友去玩的，为他们选择的就是该酒店，房间干净整洁，但是卫生间的设施太简陋，房间内有小冰箱，考虑的比较周到，如果卫生间设备好一点就更好了！服务人员的态度非常好，没有给我们青岛人丢脸，电话随叫随到。
1

('位置不错，去海滨浴场挺方便的，就是房费有点高。门口的出租车不好打，最好往北出了口再打车。服务很好，态度不错。', np.int64(1))
位置不错，去海滨浴场挺方便的，就是房费有点高。门口的出租车不好打，最好往北出了口再打车。服务很好，态度不错。
1

('酒店设备不错，也干净，但离地铁站还是有一段距离，要穿过好几个小商场，没什么路标指示，还是要问一下人。但这样的价钱，性价比算不错了。而且用港币付款，兑成人民币很划算。', np.int64(1))
酒店设备不错，也干净，但离地铁站还是有一段距离，要穿过好几个小商场，没什么路标指示，还是要问一下人。但这样的价钱，性价比算不错了。而且用港币付款，兑成人民币很划算。
1

('酒店挺不错的,接机的车也大,酒店环境也好.离公园大门不远,走走就到,路上还能拍照,很幸运遇上陈大叔给我们做导游.早餐还行.价格略贵些', np.int64(1))
酒店挺不错的,接机的车也大,酒店环境也好.离公园大门不远,走走就到,路上还能拍照,很幸运遇上陈大叔给我们做导游.早餐还行.价格略贵些
1

## Step5 创建 Dataloader

In [12]:
import torch

tokenizer = AutoTokenizer.from_pretrained("hfl/rbt3")


def collate_func(batch):
    # print("batch:", batch)

    texts, labels = [], []
    for item in batch:
        texts.append(item[0])
        labels.append(item[1])
    # print("texts:", texts)
    # print("labels:", labels)

    inputs = tokenizer(
        texts,
        max_length=128,
        padding="max_length",
        truncation=True,
        return_tensors="pt",
    )
    inputs["labels"] = torch.tensor(labels)

    return inputs


"""
batch: [
    ('房间很干净，设施很新，应该是义乌最好的酒店。宾馆反馈2008年4月14日：给您创造一个洁净的居住环境是我们的职责，愿酒店中的每一次都给您留下美好的记忆，谢谢您！', np.int64(1)),
    ('酒店的设施是很不错的，房间大，设施新，床和被子都是很新的。洗手间也是干、湿分离。服务员态度也是很好，出入都会打招呼。就是餐厅大堂中，适合2－3人吃饭的桌子太少了。还有就是房价在衢州应该属于偏高了。', np.int64(1)),
    ('入住西楼海景套房（据说离海更近一点），应该说总体很不错，有老五星的风范。服务也比较热情。可能是比较老或是空调或是近海的原因，房间内稍有一点异味。地毯厚度不够5星的。家具大都是原色的，地毯也是颜色的，不亮丽。电视陈旧，遥控器不灵了。比较好玩的是房间里的电水壶的大个头，好像还是进口的。还有早餐分中西常规、粤式(我倾向于这个)和日式的3个厅，不过只能选择其中一个，到10点结束。走廊是分片的感应灯。有夜床服务、午茶小饼干1块、枕头上会放一张别着小鲜花的印有诗句的卡纸，赞！洁具质量不好，除了肥皂。无烟楼层有客人在走廊和房间(房门洞开)抽烟，无人制止。缺少报纸供应。盥洗室放有女孩子可应急的发筋，细心，再赞一个。套房的景色很不错，离海倒是确实近，就在背后。稍微偏离一点商业区，不过不远，打车到五四广场3公里不到。补充点评2008年3月6日：差点忘了，我打车的司机径直把握开到东楼，拉门的先生还给我一张记录有车牌号的纸片，赞一下。另外，青岛的酒店服务普遍不错。不过饭店的服务员可能没听说过“菊花普洱”。', np.int64(1))
]

texts: [
    '房间很干净，设施很新，应该是义乌最好的酒店。宾馆反馈2008年4月14日：给您创造一个洁净的居住环境是我们的职责，愿酒店中的每一次都给您留下美好的记忆，谢谢您！',
    '酒店的设施是很不错的，房间大，设施新，床和被子都是很新的。洗手间也是干、湿分离。服务员态度也是很好，出入都会打招呼。就是餐厅大堂中，适合2－3人吃饭的桌子太少了。还有就是房价在衢州应该属于偏高了。',
    '入住西楼海景套房（据说离海更近一点），应该说总体很不错，有老五星的风范。服务也比较热情。可能是比较老或是空调或是近海的原因，房间内稍有一点异味。地毯厚度不够5星的。家具大都是原色的，地毯也是颜色的，不亮丽。电视陈旧，遥控器不灵了。比较好玩的是房间里的电水壶的大个头，好像还是进口的。还有早餐分中西常规、粤式(我倾向于这个)和日式的3个厅，不过只能选择其中一个，到10点结束。走廊是分片的感应灯。有夜床服务、午茶小饼干1块、枕头上会放一张别着小鲜花的印有诗句的卡纸，赞！洁具质量不好，除了肥皂。无烟楼层有客人在走廊和房间(房门洞开)抽烟，无人制止。缺少报纸供应。盥洗室放有女孩子可应急的发筋，细心，再赞一个。套房的景色很不错，离海倒是确实近，就在背后。稍微偏离一点商业区，不过不远，打车到五四广场3公里不到。补充点评2008年3月6日：差点忘了，我打车的司机径直把握开到东楼，拉门的先生还给我一张记录有车牌号的纸片，赞一下。另外，青岛的酒店服务普遍不错。不过饭店的服务员可能没听说过“菊花普洱”。'
]

labels: [np.int64(1), np.int64(1), np.int64(1)]
"""

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

"\nbatch: [\n    ('房间很干净，设施很新，应该是义乌最好的酒店。宾馆反馈2008年4月14日：给您创造一个洁净的居住环境是我们的职责，愿酒店中的每一次都给您留下美好的记忆，谢谢您！', np.int64(1)),\n    ('酒店的设施是很不错的，房间大，设施新，床和被子都是很新的。洗手间也是干、湿分离。服务员态度也是很好，出入都会打招呼。就是餐厅大堂中，适合2－3人吃饭的桌子太少了。还有就是房价在衢州应该属于偏高了。', np.int64(1)),\n    ('入住西楼海景套房（据说离海更近一点），应该说总体很不错，有老五星的风范。服务也比较热情。可能是比较老或是空调或是近海的原因，房间内稍有一点异味。地毯厚度不够5星的。家具大都是原色的，地毯也是颜色的，不亮丽。电视陈旧，遥控器不灵了。比较好玩的是房间里的电水壶的大个头，好像还是进口的。还有早餐分中西常规、粤式(我倾向于这个)和日式的3个厅，不过只能选择其中一个，到10点结束。走廊是分片的感应灯。有夜床服务、午茶小饼干1块、枕头上会放一张别着小鲜花的印有诗句的卡纸，赞！洁具质量不好，除了肥皂。无烟楼层有客人在走廊和房间(房门洞开)抽烟，无人制止。缺少报纸供应。盥洗室放有女孩子可应急的发筋，细心，再赞一个。套房的景色很不错，离海倒是确实近，就在背后。稍微偏离一点商业区，不过不远，打车到五四广场3公里不到。补充点评2008年3月6日：差点忘了，我打车的司机径直把握开到东楼，拉门的先生还给我一张记录有车牌号的纸片，赞一下。另外，青岛的酒店服务普遍不错。不过饭店的服务员可能没听说过“菊花普洱”。', np.int64(1))\n]\n\ntexts: [\n    '房间很干净，设施很新，应该是义乌最好的酒店。宾馆反馈2008年4月14日：给您创造一个洁净的居住环境是我们的职责，愿酒店中的每一次都给您留下美好的记忆，谢谢您！',\n    '酒店的设施是很不错的，房间大，设施新，床和被子都是很新的。洗手间也是干、湿分离。服务员态度也是很好，出入都会打招呼。就是餐厅大堂中，适合2－3人吃饭的桌子太少了。还有就是房价在衢州应该属于偏高了。',\n    '入住西楼海景套房（据说离海更近一点），应该说总体很不错，有老五星的风范。服务也比较热情。可能是比较老或是空调或是近海的原因，房间内稍有一点异味。地毯厚度不够5星的。家具大都是原色的，地毯也是颜色的，不亮丽。电视陈旧，遥控器不灵了。比较好玩的是房间里的电水壶的大个头，好像还是进口的。还有早餐分中西常规、粤式(我倾向于这个)和日式的3个厅，不过只能选择其中一个，到10点结束。走廊是分片的感应灯。有夜床服务、午茶小饼干1块、枕头上会放一张别着小鲜花的印有诗句的卡纸，赞！洁具质量不好，除了肥皂。无烟楼层有客人在走廊和房间(房门洞开)抽烟，无人制止。缺少报纸供应。盥洗室放有女孩子可应急的发筋，细心，再赞一个。套房的景色很不错，离海倒是确实近，就在背后。稍微偏离一点商业区，不过不远，打车到五四广场3公里不到。补充点评2008年3月6日：差点忘了，我打车的司机径直把握开到东楼，拉门的先生还给我一张记录有车牌号的纸片，赞一下。另外，青岛的酒店服务普遍不错。不过饭店的服务员可能没听说过“菊花普洱”。'\n]\n\nlabels: [np.int64(1), np.int64(1), np.int64(1)]\n"

In [13]:
# 调试
from torch.utils.data import DataLoader

trainloader = DataLoader(trainset, batch_size=3, shuffle=False, collate_fn=collate_func)

In [14]:
next(enumerate(trainloader))

(0,
 {'input_ids': tensor([[ 101,  679, 4761, 6887,  784,  720, 1333, 1728, 8024, 6821,  702, 6983,
          2421, 4680, 1184, 4638,  817, 3419,  976,  749,  678, 6444, 8024, 5445,
           684, 1453, 3314, 2233, 4197, 3300,  914, 7218,  817,  511,  679, 7231,
          8013, 6821, 3613, 1057,  857, 4638, 3221, 1920, 2414, 2791, 8024,  898,
          3191, 3221, 5165,  914, 4638, 2357, 2229, 8024, 5653, 3302, 4638, 2414,
          8024, 2600,  860, 3341, 6432, 8024, 6820, 3221, 2523,  679, 7231, 4638,
          8013,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0],
         [ 101, 7674, 1044, 6983, 2421, 2792, 1762,  855, 5390, 2523, 7391, 5929,
          8024, 4692, 3416, 2094, 3221, 5381,  677, 6370, 1296, 4638, 2145,  782,
          3683, 6772, 1914, 8024,  817, 3419,  912, 2139, 8024, 4685, 2190, 4638,
          2791, 7313, 4801,  816, 6392, 3177, 1469, 3302, 1218, 2218, 2345,  763,
           511, 2769, 2791, 2094, 4638, 4958, 6444, 4994, 4197, 3221,  702,  753,
          2797, 4638,  511,  677, 7481, 6820, 6585, 4708, 1920, 1928, 4212,  511,
          1184, 1378, 2190,  872,  738, 4263, 4415,  679, 4415, 4638,  511, 1963,
          3362, 1718,  704, 5404, 3886, 1377,  809, 5440, 5991, 6421, 6983, 2421,
          8024, 1415, 1156, 6820, 3221, 1343, 1166, 1905, 1416,  511, 5018,  753,
          1921, 2940, 4638, 6929,  702,  679, 6823, 4638, 1921, 6568, 6983, 2421,
          6820,  679, 7231,  511,  817, 3419,  738,  102],
         [ 101, 2791, 7313, 3300, 3791, 2466, 7599, 3419, 8024, 2215, 1071, 3861,
          2147, 1469, 1265, 1966, 7313, 4638, 2357, 5390,  511,  679, 6814, 3900,
          3861, 2791, 4638, 7344, 3717,  976, 4638,  679, 1962, 8024, 3819, 2130,
          4074, 3861, 2147, 1765, 7481, 1059, 3221, 3717, 8024, 2345, 4157, 3035,
          6658,  511, 2161, 7667, 1353, 7668, 8182, 2399,  125, 3299, 8111, 3189,
          8038, 7478, 2382, 2697, 6468, 2644, 4638, 1045,  707, 1469, 2190, 2769,
           812, 7649, 2421, 4638, 1068, 3800, 1469, 5507, 2137,  511, 2190,  754,
          2644, 2990, 1139, 4638,  679, 6639, 2769,  812, 2199, 1222, 1213, 3121,
          6822, 8024, 1213, 3724, 2828, 2339,  868,  976, 2533, 3291, 1962, 8024,
          5314, 2161, 2145, 2990,  897, 3291,  831, 6574,  510, 3291, 5653, 6844,
          4638, 4801,  816, 6392, 3177, 1469, 6763,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([1, 0, 1])})

In [15]:
len(trainloader)

2330

In [16]:
from torch.utils.data import DataLoader

trainloader = DataLoader(trainset, batch_size=32, shuffle=True, collate_fn=collate_func)
validloader = DataLoader(
    validset, batch_size=64, shuffle=False, collate_fn=collate_func
)

## Step6 创建模型及优化器

In [17]:
from torch.optim import Adam

model = AutoModelForSequenceClassification.from_pretrained("hfl/rbt3")

if torch.cuda.is_available():
    model = model.cuda()

model.device

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at hfl/rbt3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

device(type='cuda', index=0)

In [18]:
optimizer = Adam(model.parameters(), lr=2e-5)

## Step7 训练与验证

In [19]:
def evaluate():
    model.eval()
    acc_num = 0
    with torch.inference_mode():
        for batch in validloader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}
            output = model(**batch)
            pred = torch.argmax(output.logits, dim=-1)
            print(f"evaluate pred: {pred.long()}, labels: {batch["labels"].long()}")
            acc_num += (pred.long() == batch["labels"].long()).float().sum()
    return acc_num / len(validset)


def train(epoch=3, log_step=10):
    global_step = 0

    for ep in range(epoch):
        model.train()
        # 每个 epoch 训练全部数据
        for batch in trainloader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}

            optimizer.zero_grad()
            output = model(**batch)
            output.loss.backward()
            optimizer.step()

            if global_step % log_step == 0:
                print(
                    f"ep: {ep}, global_step: {global_step}, loss: {output.loss.item()}"
                )

            global_step += 1

        acc = evaluate()
        print(f"ep: {ep}, acc: {acc}")

## Step8 模型训练

In [20]:
train()

ep: 0, global_step: 0, loss: 0.6792185306549072
ep: 0, global_step: 10, loss: 0.6717472672462463
ep: 0, global_step: 20, loss: 0.5255171060562134
ep: 0, global_step: 30, loss: 0.6477005481719971
ep: 0, global_step: 40, loss: 0.4597216546535492
ep: 0, global_step: 50, loss: 0.23783189058303833
ep: 0, global_step: 60, loss: 0.34171104431152344
ep: 0, global_step: 70, loss: 0.40657153725624084
ep: 0, global_step: 80, loss: 0.2790922522544861
ep: 0, global_step: 90, loss: 0.4268070459365845
ep: 0, global_step: 100, loss: 0.20245224237442017
ep: 0, global_step: 110, loss: 0.2992611229419708
ep: 0, global_step: 120, loss: 0.32032665610313416
ep: 0, global_step: 130, loss: 0.23053929209709167
ep: 0, global_step: 140, loss: 0.33635789155960083
ep: 0, global_step: 150, loss: 0.25556808710098267
ep: 0, global_step: 160, loss: 0.26895344257354736
ep: 0, global_step: 170, loss: 0.2611411213874817
ep: 0, global_step: 180, loss: 0.3623621463775635
ep: 0, global_step: 190, loss: 0.21829186379909515
ep: 0, global_step: 200, loss: 0.261199414730072
ep: 0, global_step: 210, loss: 0.19439885020256042
evaluate pred: tensor([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], device='cuda:0'), labels: tensor([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0], device='cuda:0'), labels: tensor([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1], device='cuda:0'), labels: tensor([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], device='cuda:0'), labels: tensor([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0], device='cuda:0'), labels: tensor([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0], device='cuda:0'), labels: tensor([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], device='cuda:0'), labels: tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0], device='cuda:0'), labels: tensor([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0], device='cuda:0')
evaluate pred: tensor([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1], device='cuda:0'), labels: tensor([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 1, 1, 1, 1, 1, 0, 1], device='cuda:0'), labels: tensor([1, 1, 1, 1, 1, 1, 0, 1], device='cuda:0')
ep: 0, acc: 0.8853092789649963
ep: 1, global_step: 220, loss: 0.1581215262413025
ep: 1, global_step: 230, loss: 0.30219000577926636
ep: 1, global_step: 240, loss: 0.27379801869392395
ep: 1, global_step: 250, loss: 0.14497706294059753
ep: 1, global_step: 260, loss: 0.18102434277534485
ep: 1, global_step: 270, loss: 0.4022076725959778
ep: 1, global_step: 280, loss: 0.2090064138174057
ep: 1, global_step: 290, loss: 0.3456347584724426
ep: 1, global_step: 300, loss: 0.2153044193983078
ep: 1, global_step: 310, loss: 0.2638348937034607
ep: 1, global_step: 320, loss: 0.2395157814025879
ep: 1, global_step: 330, loss: 0.2701161503791809
ep: 1, global_step: 340, loss: 0.2141427993774414
ep: 1, global_step: 350, loss: 0.17347881197929382
ep: 1, global_step: 360, loss: 0.3236008882522583
ep: 1, global_step: 370, loss: 0.13602831959724426
ep: 1, global_step: 380, loss: 0.26403334736824036
ep: 1, global_step: 390, loss: 0.30729085206985474
ep: 1, global_step: 400, loss: 0.2778412401676178
ep: 1, global_step: 410, loss: 0.20840099453926086
ep: 1, global_step: 420, loss: 0.11831019818782806
ep: 1, global_step: 430, loss: 0.3583301305770874
evaluate pred: tensor([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], device='cuda:0'), labels: tensor([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0], device='cuda:0'), labels: tensor([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1], device='cuda:0'), labels: tensor([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], device='cuda:0'), labels: tensor([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0], device='cuda:0'), labels: tensor([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0], device='cuda:0'), labels: tensor([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], device='cuda:0'), labels: tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0], device='cuda:0'), labels: tensor([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0], device='cuda:0')
evaluate pred: tensor([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1], device='cuda:0'), labels: tensor([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 1, 1, 1, 0, 0], device='cuda:0'), labels: tensor([1, 1, 1, 1, 1, 1, 0, 1], device='cuda:0')
ep: 1, acc: 0.894329845905304
ep: 2, global_step: 440, loss: 0.20848384499549866
ep: 2, global_step: 450, loss: 0.29187750816345215
ep: 2, global_step: 460, loss: 0.18178316950798035
ep: 2, global_step: 470, loss: 0.14918458461761475
ep: 2, global_step: 480, loss: 0.25388461351394653
ep: 2, global_step: 490, loss: 0.3403012752532959
ep: 2, global_step: 500, loss: 0.2800768315792084
ep: 2, global_step: 510, loss: 0.23723208904266357
ep: 2, global_step: 520, loss: 0.10935322195291519
ep: 2, global_step: 530, loss: 0.1094675064086914
ep: 2, global_step: 540, loss: 0.09804124385118484
ep: 2, global_step: 550, loss: 0.1561996340751648
ep: 2, global_step: 560, loss: 0.1848713606595993
ep: 2, global_step: 570, loss: 0.16138796508312225
ep: 2, global_step: 580, loss: 0.06463777273893356
ep: 2, global_step: 590, loss: 0.08568419516086578
ep: 2, global_step: 600, loss: 0.24872128665447235
ep: 2, global_step: 610, loss: 0.1898629069328308
ep: 2, global_step: 620, loss: 0.05418146401643753
ep: 2, global_step: 630, loss: 0.3023713231086731
ep: 2, global_step: 640, loss: 0.3051486015319824
ep: 2, global_step: 650, loss: 0.11585734039545059
evaluate pred: tensor([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], device='cuda:0'), labels: tensor([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0], device='cuda:0'), labels: tensor([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1], device='cuda:0'), labels: tensor([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], device='cuda:0'), labels: tensor([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1], device='cuda:0')
evaluate pred: tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1], device='cuda:0'), labels: tensor([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1], device='cuda:0')
evaluate pred: tensor([1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0], device='cuda:0'), labels: tensor([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0], device='cuda:0'), labels: tensor([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0], device='cuda:0')
evaluate pred: tensor([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## Step9 模型预测

In [21]:
sen = "我觉得这家酒店不错，饭很好吃！"
id2_label = {0: "差评！", 1: "好评！"}
model.eval()
with torch.inference_mode():
    inputs = tokenizer(sen, return_tensors="pt")
    inputs = {k: v.cuda() for k, v in inputs.items()}
    output = model(**inputs)
    print(f"output: {output}")
    logits = output.logits
    print(f"logits: {logits}")
    pred = torch.argmax(logits, dim=-1)
    print(f"pred: {pred}")
    print(f"输入: {sen}\n模型预测结果:{id2_label.get(pred.item())}")

output: SequenceClassifierOutput(loss=None, logits=tensor([[-3.1057,  2.8289]], device='cuda:0'), hidden_states=None, attentions=None)
logits: tensor([[-3.1057,  2.8289]], device='cuda:0')
pred: tensor([1], device='cuda:0')
输入: 我觉得这家酒店不错，饭很好吃！
模型预测结果:好评！

In [22]:
from transformers import pipeline

model.config.id2label = id2_label
pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

Device set to use cuda:0

In [23]:
pipe(sen)

[{'label': '好评！', 'score': 0.9973605275154114}]